title: Our Pie Shop
author: Awa D.
email: my_email@address.com
description: > # this means to ignore newlines until "baseurl:"
  Theses pies can be ordered, delivered, or picked up. We have a variety of pies available from apple pies to cherry pies. We also have drinks and bagels available as well.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
